Rework cdm path logic
glennguy/script.module.drmhelper pull request #4
Opened 2019-04-20 13:18 UTC by glennguy

* CDM now downloads to home folder regardless of destination which fixes some permissions problems seen on windows users not running as admin.

* variable names used in unarchiving/copying commands for clarity

* Removed ssd checking as ssd_wv module is always included as part of inputstream.adaptive as of 18, and 17 is no longer supported for DRM.

* Checks to see if destination folder is writeable and if not set the DECRYPTERPATH i.a setting to the default of special://home/cdm as it will be writeable.

2019-04-20 13:19 UTC, glennguy commented
@andybotting 

Tested on win64, rpi3 librelec and x86_64 libreelec.

 One thing I'm unsure about is my eval() trickery with the cdm paths in the config, is it too error prone? Or should tests be the solution?

2019-04-20 22:49 UTC, andybotting requested changes
I think your logic is sound, and code looks ok with just one comment.

2019-04-20 22:49 UTC, andybotting commented on lib/drmhelper/helper.py
> +            os.path.isfile(os.path.join(p, cdm_fn)) for p in config.CDM_PATHS):
Should this one be `cdm_paths` instead?

2019-04-20 22:49 UTC, andybotting commented on lib/drmhelper/helper.py
> +        return [eval(x) for x in config.CDM_PATHS]
It is a little funky, but I think it's ok +1

2019-04-21 00:09 UTC, glennguy commented on lib/drmhelper/helper.py
> +            os.path.isfile(os.path.join(p, cdm_fn)) for p in config.CDM_PATHS):
whoops

2019-05-01 06:14 UTC, merged